### ISSUE TITLE
AttributeError: add_request_method

### ISSUE THREAD

**Issue by piotrektt** [Pylons/pyramid_blogr#12]
(pyramid)piotrektt@BlackSun:~/Projects/pyramid/pyramid_blogr$ pserve --reload development.ini 
Starting subprocess with file monitor
Traceback (most recent call last):
  File "/home/piotrektt/Projects/pyramid/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.3.4', 'console_scripts', 'pserve')()
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 47, in main
    return command.run()
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 290, in run
    relative_to=base, global_conf=vars)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 318, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/piotrektt/Projects/pyramid/pyramid_blogr/pyramid_blogr/__init__.py", line 11, in main
    config = Configurator(settings=settings)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 304, in __init__
    exceptionresponse_view=exceptionresponse_view,
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 426, in setup_registry
    self.include(inc)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 737, in include
    c(configurator)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 138, in includeme
    config.add_request_method('pyramid_tm.create_tm', name='tm', reify=True)
  File "/home/piotrektt/Projects/pyramid/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 775, in __getattr__
    raise AttributeError(name)
AttributeError: add_request_method

**Comment by ergo** [comment]
Try to use latest pyramid 1.5.x or even 1.6?
This looks like some version incompatiblility between pyramid_tm and pyramid itself.

**Comment by piotrektt** [comment]
That worked. I updated pyramid to 1.57. Thx for help.

**Comment by mmerickel** [comment]
The version of `pyramid_tm` that uses `add_request_method` is unreleased. How did it end up in your virtualenv?

**Comment by piotrektt** [comment]
I don't know. I created virtual env. Inside the env I did "pip install pyramid==1.3.4", then I followed instructions from pyramid_blogr (http://pyramid-blogr.readthedocs.org/en/latest/project_structure.html). When I wanted to pserve I got this error. 

My system: Ubuntu 14.04.2 LTS x64
